name: trading-bot-simple
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - matplotlib
  - numpy
  - pip
  - pip:
    - yfinance
    - backtrader
    - seaborn
    - pytest
    - pytest-cov
    - coverage