name: trading-bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=2.0.0
  - numpy>=1.24.0
  - matplotlib>=3.7.0
  - jupyter>=1.0.0
  - pytest>=7.0.0
  - mypy>=1.0.0
  - cryptography>=41.0.0
  - python-dotenv>=1.0.0
  - requests>=2.31.0
  - sqlalchemy>=2.0.0
  - psycopg2>=2.9.0
  - redis-py>=4.5.0
  - pip
  - pip:
    - backtrader>=1.9.78
    - yfinance>=0.2.0
    - ruff>=0.1.0
    - alpha-vantage>=2.3.0
    - ccxt>=4.0.0
    - ta-lib>=0.4.0
    - scipy>=1.11.0
    - scikit-learn>=1.3.0
    - plotly>=5.15.0
    - dash>=2.14.0
    - fastapi>=0.100.0
    - uvicorn>=0.23.0
    - pydantic>=2.0.0
    - python-multipart>=0.0.6